// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkaJMmv_1Cln7kKCjxte-Qr-HZptjs_w',
    appId: '1:829426376519:web:6d2b00583c8569e4fff662',
    messagingSenderId: '829426376519',
    projectId: 'proyecto-estadio',
    authDomain: 'proyecto-estadio.firebaseapp.com',
    storageBucket: 'proyecto-estadio.firebasestorage.app',
    measurementId: 'G-ELH8544Y93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR00NsRdiRcVqggQWL93DhxV4K39fFNgk',
    appId: '1:829426376519:android:073186d8ca797aacfff662',
    messagingSenderId: '829426376519',
    projectId: 'proyecto-estadio',
    storageBucket: 'proyecto-estadio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARC2s9el86_fejxTGLjSNov9_yMhtizCo',
    appId: '1:829426376519:ios:794b09af2f682ad5fff662',
    messagingSenderId: '829426376519',
    projectId: 'proyecto-estadio',
    storageBucket: 'proyecto-estadio.firebasestorage.app',
    iosBundleId: 'com.example.proyectoEstadio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARC2s9el86_fejxTGLjSNov9_yMhtizCo',
    appId: '1:829426376519:ios:794b09af2f682ad5fff662',
    messagingSenderId: '829426376519',
    projectId: 'proyecto-estadio',
    storageBucket: 'proyecto-estadio.firebasestorage.app',
    iosBundleId: 'com.example.proyectoEstadio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbkaJMmv_1Cln7kKCjxte-Qr-HZptjs_w',
    appId: '1:829426376519:web:cb42c30bdc19bff1fff662',
    messagingSenderId: '829426376519',
    projectId: 'proyecto-estadio',
    authDomain: 'proyecto-estadio.firebaseapp.com',
    storageBucket: 'proyecto-estadio.firebasestorage.app',
    measurementId: 'G-PRJDNTH07G',
  );
}
